### PR TITLE
Last temporal deduction integration fixes

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ntoxeg** [comment]
You have modified notebooks — remember to invoke `nbdev_build_lib` and `black` or just `make rocca`.

**Comment by ngeiswei** [comment]
I'm having some unusual error `cannot import name 'html5lib' from 'pip._vendor'` but I presume it might come you, @ntoxeg, updating the image or such.  Also note, @ntoxeg, you'll probably want to rebase #37 (I mean the subsequent one) onto the master cause much of it (black formatting) is present in that PR.

**Comment by ntoxeg** [comment]
@ngeiswei I’m working on bringing Python 3.10 into the image and doing this properly turned out to be a major pain — specifically there are problems with pip…

**Comment by ngeiswei** [comment]
@ntoxeg, if Python 3.9 is less of a pain, it's OK too.  In terms of type system they're almost the same (Python 3.10 has union type, which is cool, but not dramatically so).

**Comment by ntoxeg** [comment]
@ngeiswei well, that would require you to pull back some type annotations you’ve made — at this point I’ve made enough progress that I’ll try to see it through, unless I get horribly stuck today I’ll go for 3.10. The thing is, once I have this figured out, then in principle we will always be able to update to the latest Python, if we wish.

**Comment by ntoxeg** [comment]
@ngeiswei unfortunately I’ve hit a worse-case scenario as it turns out CMake scripts for OpenCog can’t handle multiple Python versions in the system. This means that you can’t use *any* other Python until I figure out how to improve them and get PRs of that merged. Fortunately CMake nowadays has its own Python support so hopefully migrating to that will fix these issues.
